# This is a basic workflow to help you get started with Actions

name: Testing workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '8.11.1'                # set this to the node version to use

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Run Command
      run: |
          ls
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'App.zip'
        exclusions: '*.git*'
        path: ./AllInOneAngular5/src
    
 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: app-code
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/App.zip    
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [build]
    steps:
      - name: list dirs
        run: ls
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: app-code
          # Destination path
          path: ${{ github.workspace }}/src
      - name: list dirs
        run: ls
